export const categories = [
  {
    id: 1,
    title: "card and stationery",
    slug: "card-and-stationery",
    description:
      "Voluptas numquam debitis enim saepe quisquam consequuntur. A sit omnis laboriosam dolor doloribus. Nostrum ipsum quisquam distinctio nesciunt qui cupiditate consequatur.",
    meta_title: "card and stationery",
    meta_description:
      "Est est neque nostrum sapiente error. Fugit quis repellendus sint eum non nesciunt quod. Beatae laudantium odio id sit unde et dicta inventore.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 2,
        title: "Standard Business Cards",
        slug: "standard-business-cards",
        description:
          "Nostrum perspiciatis accusamus molestiae illo itaque recusandae natus. Hic ipsa assumenda laborum soluta blanditiis. Rerum rem quos ducimus quo neque quis omnis maiores.",
        meta_title: "Standard Business Cards",
        meta_description:
          "Illo et modi blanditiis quas. Veritatis in ut accusantium qui tenetur sed. Similique cumque enim maxime quam. In consequatur repellat eos.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 3,
        title: "NCR Printing",
        slug: "ncr-printing",
        description:
          "Ratione neque repellendus amet enim nemo beatae omnis non. Consequuntur consequatur quidem voluptas cum. Aut rerum consequuntur aliquam aliquid. Beatae ut et ratione quidem ullam porro animi.",
        meta_title: "NCR Printing",
        meta_description:
          "Autem qui ut ea quis labore voluptatem. Beatae quis autem libero nobis. Sapiente neque sunt ea numquam voluptate nobis.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 4,
        title: "Luxury Business Cards",
        slug: "luxury-business-cards",
        description:
          "Enim saepe iste qui esse. Occaecati omnis in laborum provident vel non voluptatem. Debitis odio aliquid porro eaque odit.",
        meta_title: "Luxury Business Cards",
        meta_description:
          "Quis eos error voluptatem repellendus aut nam. Exercitationem deserunt qui blanditiis pariatur. Assumenda numquam repudiandae et soluta qui. Neque unde error et.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 5,
        title: "Cards By Type",
        slug: "cards-by-type",
        description:
          "Et ut nisi dolores distinctio. Vitae vel et perspiciatis enim corrupti aut. Ratione qui enim architecto cumque harum et aperiam.",
        meta_title: "Cards By Type",
        meta_description:
          "Quia odio repellat reprehenderit tempora rem amet. Ut placeat ullam dolores aut labore. Impedit quos inventore sit aperiam nobis adipisci voluptate necessitatibus.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 6,
        title: "Stationery Printing",
        slug: "stationery-printing",
        description:
          "Itaque et rem ut eligendi. Cum odit et eaque explicabo dolores quia. Animi delectus alias tempore et libero occaecati.",
        meta_title: "Stationery Printing",
        meta_description:
          "Voluptatem praesentium qui soluta voluptas voluptatum occaecati rerum. Cum dolorem quas minus sint et dolor delectus. Voluptas aperiam quo libero aut eum et.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 7,
        title: "Pens & Pencils",
        slug: "pens-pencils",
        description:
          "Dolorem velit earum voluptatem natus est ut. Eligendi ut consequatur omnis repellat. Tempora fugiat amet ratione sit. Doloribus ut qui ipsam numquam dolor.",
        meta_title: "Pens & Pencils",
        meta_description:
          "Velit eum quia quia quas voluptatem laudantium nisi. Est aut blanditiis dolorum officia eius. Aut nihil sit ut mollitia.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 8,
        title: "Cards & Invitations",
        slug: "cards-invitations",
        description:
          "Veniam sit optio natus veritatis fuga rerum aut. Aperiam hic consequatur commodi quasi deleniti. Voluptatibus incidunt tenetur officia corporis officia rem. Qui et est iure quasi earum qui dolor quos.",
        meta_title: "Cards & Invitations",
        meta_description:
          "Dolores itaque cum ut accusantium quis. Magni consequatur qui accusantium repellat repudiandae. Minima tenetur voluptatem velit soluta quaerat. Quo necessitatibus nihil pariatur asperiores ipsum.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 9,
        title: "Folders",
        slug: "folders",
        description:
          "Eligendi aut dolorem perspiciatis blanditiis ut et numquam. Nulla fugiat dolores velit omnis incidunt quibusdam eum repudiandae. Officiis perferendis nam incidunt rem.",
        meta_title: "Folders",
        meta_description:
          "Necessitatibus aliquid doloremque at nobis ut natus saepe rerum. Rerum nesciunt rerum fugit. Porro rerum id facere earum animi ut.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 10,
        title: "Calendars",
        slug: "calendars",
        description:
          "Non non sequi magnam sit. Qui excepturi vel qui magni. Omnis consequatur et repudiandae sit voluptas.",
        meta_title: "Calendars",
        meta_description:
          "Qui vel omnis aut dolorum cum quia. Accusantium quibusdam numquam cum deserunt laborum unde. Qui quod ea magni reiciendis. Voluptatem reprehenderit doloremque expedita quibusdam dolor.",
        status: "Active",
        category_id: 1,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 11,
    title: "Large Format Printing",
    slug: "large-format-printing",
    description:
      "Enim vero est saepe totam sequi dolorum. Praesentium exercitationem hic asperiores odio. Fuga cumque et ea iste magnam.",
    meta_title: "Large Format Printing",
    meta_description:
      "Dicta tempora asperiores natus laborum a non aut. Quae odit consequatur aspernatur aperiam ea. Nulla voluptatum qui qui autem culpa.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 12,
        title: "A-Boards",
        slug: "a-boards",
        description:
          "Voluptates veritatis porro saepe vel delectus aspernatur. Sunt error iste nam deleniti laudantium impedit voluptatum. Nihil quam aut animi dolor dolorem temporibus non aut.",
        meta_title: "A-Boards",
        meta_description:
          "Quas quisquam omnis assumenda aut fuga quos. Impedit facilis atque voluptatem alias itaque officiis. Odit delectus iste voluptas molestias ad.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 13,
        title: "A-Boards 2",
        slug: "a-boards-2",
        description:
          "Illum sed eos illum vel et eveniet quia sunt. Perspiciatis at molestias mollitia dolorum sed. Delectus deserunt autem dolore ut aliquam praesentium.",
        meta_title: "A-Boards",
        meta_description:
          "Libero accusamus aut fugiat numquam voluptatem molestiae quam. Culpa sed in eos ut necessitatibus. Dolor eos ut doloremque.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 14,
        title: "Flags",
        slug: "flags",
        description:
          "Perferendis sapiente ea et velit incidunt. Quaerat animi porro veniam rerum quia ut. Quaerat quis molestias eos beatae atque. Quo tempora aut dolorum quas fugiat amet dolor.",
        meta_title: "Flags",
        meta_description:
          "Excepturi molestiae commodi sed est nostrum. Enim nisi debitis excepturi vel corporis aperiam voluptates unde. At cum in quisquam alias aspernatur impedit est. Sit nostrum consequatur rerum est. Voluptatem quia quisquam velit.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 15,
        title: "Large Posters",
        slug: "large-posters",
        description:
          "Non hic voluptatem ut voluptatibus minus quibusdam. Necessitatibus animi minima ea fuga voluptas necessitatibus.",
        meta_title: "Large Posters",
        meta_description:
          "Sunt architecto saepe commodi incidunt et reiciendis. Ab ea voluptatem ut.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 16,
        title: "Banner Printing",
        slug: "banner-printing",
        description:
          "Tempore occaecati distinctio repellendus doloremque odit nobis est. Inventore libero eligendi aut eos quia. Sequi eligendi ipsam nisi quis occaecati. Voluptatibus amet ducimus cupiditate vel.",
        meta_title: "Banner Printing",
        meta_description:
          "Minima eligendi beatae eaque et amet voluptatem mollitia. Quisquam qui commodi odio rerum dolores soluta rerum. Pariatur et maiores sed sit voluptatem ipsam ea. Vel aperiam error vitae voluptas officia odit ad.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 17,
        title: "Board Printing",
        slug: "board-printing",
        description:
          "Ad voluptatibus porro sequi eum aut provident. Veritatis eum enim deleniti deleniti saepe non. Et amet quia ut atque voluptas suscipit. Veniam consequatur debitis voluptates dolor in molestiae dolorem. Soluta architecto adipisci earum aspernatur.",
        meta_title: "Board Printing",
        meta_description:
          "Qui rerum molestiae earum consequuntur omnis incidunt. Ratione reprehenderit id pariatur. Eum aut in fugiat qui hic omnis quo. Ut nulla id possimus ullam numquam consequuntur et qui.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 18,
        title: "Cardboard Display",
        slug: "cardboard-display",
        description:
          "Aperiam blanditiis qui minus pariatur debitis qui qui. Iusto aspernatur labore ipsum ea et quae maiores. Eligendi in dignissimos in aut dolorem velit qui animi.",
        meta_title: "Cardboard Display",
        meta_description:
          "At suscipit blanditiis sed at non sunt incidunt. Nemo pariatur accusantium ut dolores.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 19,
        title: "Vinyl Graphics",
        slug: "vinyl-graphics",
        description:
          "Dolor dicta repudiandae itaque saepe. Non est ut earum exercitationem saepe unde quas inventore. Aut eveniet rerum doloremque mollitia architecto.",
        meta_title: "Vinyl Graphics",
        meta_description:
          "Repellat ex ex vel at. Dolore eius sapiente dolorum in. Voluptatem debitis magnam dolorum qui voluptas occaecati.",
        status: "Active",
        category_id: 11,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 20,
    title: "Flyers & Leaflets",
    slug: "flyers-leaflets",
    description:
      "Est impedit impedit quasi eius. A provident quasi repudiandae labore sed.",
    meta_title: "Flyers & Leaflets",
    meta_description:
      "Deleniti sit reprehenderit maxime reprehenderit asperiores. Qui ipsam autem ut cum expedita iste omnis. Rem sapiente ut voluptatem. Iure non voluptatibus itaque odit quos quia dolorem. Quidem reiciendis facere eaque dolores hic dolores sed sunt.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 21,
        title: "Flyers By Type",
        slug: "flyers-by-type",
        description:
          "Sit illo vel minus consequatur consequatur inventore. Voluptatum at veritatis quasi molestiae qui labore rerum. Accusantium architecto dolorem et ut nobis ut.",
        meta_title: "Flyers By Type",
        meta_description:
          "Ea nihil veritatis consectetur est rerum. Consequatur qui laborum voluptas repellat expedita qui. Reprehenderit error placeat hic voluptates commodi autem aut.",
        status: "Active",
        category_id: 20,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 22,
        title: "Flyers By Material",
        slug: "flyers-by-material",
        description:
          "Tempore tenetur molestiae quo ratione neque qui est. Voluptate natus reprehenderit ut autem eum. Et dolorem odit nobis exercitationem impedit dicta non. Eius sint dolor minus ratione rem excepturi perspiciatis.",
        meta_title: "Flyers By Material",
        meta_description:
          "Sint laborum laudantium rerum porro qui architecto qui eveniet. Placeat similique omnis necessitatibus occaecati ut et. Nisi qui delectus est ipsa quasi. Quia aut totam neque voluptatem architecto voluptatem deserunt.",
        status: "Active",
        category_id: 20,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 23,
        title: "Menus & Hospitality",
        slug: "menus-hospitality",
        description:
          "Occaecati dolores autem saepe a est. Aut nostrum dolores omnis et voluptatem debitis. Enim iure libero neque accusamus. Quis rerum ipsa quia non consequatur dolor amet quas.",
        meta_title: "Menus & Hospitality",
        meta_description:
          "Est dicta culpa voluptatem. Facere explicabo dolorum cum quidem praesentium adipisci pariatur. Velit sit maiores nihil minus quo repellat praesentium consequatur. Similique voluptate quis accusantium magnam autem voluptatem suscipit. Ut aut atque velit quod.",
        status: "Active",
        category_id: 20,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 24,
        title: "Leaflets",
        slug: "leaflets",
        description:
          "Et recusandae ullam aut. Eius et aliquam sed eligendi suscipit.",
        meta_title: "Leaflets",
        meta_description:
          "Corporis laboriosam tempore magnam quas sint ad magnam quis. Ut quae deserunt est magni aut. Ipsa quia ullam in quo et reprehenderit atque et. Voluptas incidunt autem unde optio sequi qui in.",
        status: "Active",
        category_id: 20,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 25,
        title: "Unfinished Sheets",
        slug: "unfinished-sheets",
        description:
          "Incidunt non in nam veritatis deleniti consequatur soluta. Nemo sit reprehenderit et quo quia illum. Aut voluptas dolores consequatur aut. Eos praesentium minima tempora ea eaque dolor harum.",
        meta_title: "Unfinished Sheets",
        meta_description:
          "Ratione omnis eum voluptas ut repudiandae. Beatae officiis facere molestias aut illum modi. Id repudiandae laboriosam est. Aut libero et quod tenetur rerum eius.",
        status: "Active",
        category_id: 20,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 26,
    title: "Booklets & Brochures",
    slug: "booklets-brochures",
    description:
      "Suscipit provident qui omnis. Architecto ea vero autem aut eos. Aut iste dolorem officia aut.",
    meta_title: "Booklets & Brochures",
    meta_description:
      "Maxime commodi hic consequatur dolore optio repudiandae consectetur. Voluptatem exercitationem blanditiis quae quo dolor quo. Eius similique voluptatem cupiditate saepe explicabo eligendi saepe ducimus. Deserunt neque enim ducimus ullam id omnis adipisci.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 27,
        title: "Books, Booklets & Brochures",
        slug: "books-booklets-brochures",
        description:
          "Praesentium maiores libero aliquam distinctio est vel. Tempore aut alias magni. Nihil porro quibusdam repellendus architecto doloremque et ut dolorem.",
        meta_title: "Books, Booklets & Brochures",
        meta_description:
          "Enim enim tempora voluptas corrupti officiis autem neque atque. Aliquid aut eveniet distinctio in praesentium molestiae voluptas. Aut quo maxime totam ad in. Dicta recusandae animi et porro commodi accusamus.",
        status: "Active",
        category_id: 26,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 28,
        title: "Booklets By Size",
        slug: "booklets-by-size",
        description:
          "Earum dolore doloremque voluptates debitis qui. Enim qui rerum nisi distinctio in dicta dolor.",
        meta_title: "Booklets By Size",
        meta_description:
          "Sit aut eius aut nesciunt ratione nulla tempore. Architecto impedit rerum odit ut.",
        status: "Active",
        category_id: 26,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 29,
        title: "Booklets By Type",
        slug: "booklets-by-type",
        description:
          "Totam facilis quibusdam nulla consequatur et. Impedit voluptatem minus eos dolores eaque maxime. Quos dolorem aut esse officiis. Quidem aut rerum modi non repellat eaque. Voluptas adipisci sit et.",
        meta_title: "Booklets By Type",
        meta_description:
          "Voluptatem soluta occaecati ut error optio accusantium laudantium cumque. Dolores voluptatem libero adipisci culpa et. Doloribus officia voluptatum sint voluptate alias nihil. Quia maiores quam ea est et culpa. Aut id ratione eaque tempore sed ut at.",
        status: "Active",
        category_id: 26,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 30,
        title: "Booklet & Brochure Displays Stands",
        slug: "booklet-brochure-displays-stands",
        description:
          "Illo consectetur blanditiis nesciunt. Suscipit est qui similique et id. Dolorum facere aspernatur doloribus maxime incidunt quia commodi. Molestiae quidem dolor iusto rem voluptate.",
        meta_title: "Booklet & Brochure Displays Stands",
        meta_description:
          "Ullam harum exercitationem distinctio libero quidem non sit et. Occaecati nisi ullam rerum ut dolores quos. Dicta nisi et quae alias aut ducimus.",
        status: "Active",
        category_id: 26,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 31,
    title: "Exhibitions & Display",
    slug: "exhibitions-display",
    description:
      "Accusantium nostrum doloremque est blanditiis. Dolor nesciunt tempora qui quas provident. Maiores ut doloribus quo blanditiis labore at quasi. Nobis occaecati occaecati autem aut laborum eum.",
    meta_title: "Exhibitions & Display",
    meta_description:
      "Minus delectus autem in minus. Officia nihil sequi sit reprehenderit dolores et velit aspernatur. Doloremque et nostrum nesciunt.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 32,
        title: "Exhibition A-boards",
        slug: "exhibition-a-boards",
        description:
          "Omnis nobis odio exercitationem reprehenderit recusandae natus. Ut doloribus dolores et aut nisi quam saepe a. Impedit ut voluptatem accusamus culpa assumenda. Ratione enim aut et.",
        meta_title: "Exhibition A-boards",
        meta_description:
          "Voluptatem magnam voluptatem soluta adipisci sit cum quam pariatur. Molestiae deserunt ratione tempore ex aperiam magnam odio dolores. Enim quisquam totam autem asperiores iste et adipisci. Autem velit molestiae officiis quia non eaque. Rerum consequatur quos vel consequatur doloremque ipsam.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 33,
        title: "Exhibition A-boards 2",
        slug: "exhibition-a-boards-2",
        description:
          "Hic aliquam sunt sit soluta molestiae. Ut corrupti voluptatem aut ex dolores qui est fuga. Nihil alias possimus et ipsam.",
        meta_title: "Exhibition A-boards 2",
        meta_description:
          "Repellat earum omnis enim hic eligendi non est. Officia alias blanditiis est qui. Dolorem distinctio maxime voluptatem soluta quo.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 34,
        title: "Flags 2",
        slug: "flags-2",
        description:
          "Expedita magnam sit aut in praesentium sed nesciunt. Autem in at ipsa repudiandae rerum. Est eum eaque a delectus. Ut quia earum omnis magni sunt rem.",
        meta_title: "Flags 2",
        meta_description:
          "Expedita itaque et aut et natus voluptatum tempora harum. Deleniti blanditiis ut et non dolores eum nisi. Unde laborum quibusdam libero incidunt sapiente velit. Quo et eum odio id ratione voluptate.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 35,
        title: "Banners",
        slug: "banners",
        description:
          "Laborum doloribus tempora libero et quod doloribus sed asperiores. Et reiciendis voluptates deleniti et laborum inventore aut alias. Soluta aspernatur corporis harum est eos fugit est.",
        meta_title: "Banners",
        meta_description:
          "At ex facere qui quo. Eaque officia sunt vero consequatur. Amet eos ipsum qui quia deleniti.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 36,
        title: "Cardboard Display Stands",
        slug: "cardboard-display-stands",
        description:
          "Quam tenetur modi amet vel. Modi vitae voluptatibus libero odio doloribus aspernatur. Quisquam voluptas doloribus occaecati magnam reiciendis soluta et. Aliquam unde odit dolorum deleniti vitae deleniti.",
        meta_title: "Cardboard Display Stands",
        meta_description:
          "Qui reprehenderit recusandae nesciunt sequi. Sequi at unde tempora ullam rerum fugit. Quo et qui fuga optio veniam. Ipsa reiciendis veniam quo dolorum esse.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 37,
        title: "Exhibition Stands",
        slug: "exhibition-stands",
        description:
          "Sed similique asperiores debitis officiis eos corrupti ea delectus. Sequi dolor harum nemo rerum architecto. Doloremque explicabo sequi porro facilis.",
        meta_title: "Exhibition Stands",
        meta_description:
          "Fuga laudantium possimus dolor unde qui est incidunt quisquam. Inventore eum adipisci rerum. Rem eum ea eius rerum.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 38,
        title: "Board 2",
        slug: "board-printing-2",
        description:
          "Qui eaque amet ut ipsam. Aspernatur consequatur ut tempora alias qui accusantium. Quas voluptatum reiciendis rerum ea ut corporis. Eum nobis praesentium quis voluptas deserunt ullam sit.",
        meta_title: "Board Printing 2",
        meta_description:
          "Cum eaque laborum dolorum non repellendus. Non est tempora consequatur. Aliquid qui quia dignissimos error vel.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 39,
        title: "Lanyards",
        slug: "lanyards",
        description:
          "Ut reprehenderit aut autem porro odit ut. Saepe atque quisquam ut aspernatur velit sapiente officia. Eum eos voluptas ad veritatis voluptatem. Voluptatum molestiae laborum dolor voluptas aut.",
        meta_title: "Lanyards",
        meta_description:
          "Voluptatum nesciunt ullam assumenda quasi non ab. Asperiores magni voluptatem ut doloremque excepturi quas. Quos earum qui repellat vitae sunt consequuntur. Soluta architecto et molestiae ab. Dolor nulla earum vero.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 40,
        title: "Lanyard Cards",
        slug: "lanyard-cards",
        description:
          "Nesciunt odio veniam eligendi quibusdam voluptatum necessitatibus aut perspiciatis. Laborum et provident autem et ipsa debitis sequi dignissimos. Qui odio amet et ipsa.",
        meta_title: "Lanyard Cards",
        meta_description:
          "Quas accusamus repudiandae voluptas eos enim iusto facere. Pariatur laboriosam laborum odit corrupti dolor laudantium et. Voluptatibus dolorem dolor est eum cupiditate.",
        status: "Active",
        category_id: 31,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 41,
    title: "Signs & Posters",
    slug: "signs-posters",
    description:
      "Est qui ullam vero necessitatibus. Commodi sed ratione quibusdam vero commodi. Recusandae molestias minus dolorem tenetur omnis blanditiis unde. Magnam cum quo voluptas ea officia nulla impedit.",
    meta_title: "Signs & Posters",
    meta_description:
      "Assumenda repudiandae accusantium cupiditate accusamus. Non eligendi sed sint corrupti id voluptas nobis. Temporibus unde veritatis praesentium autem et eum ipsa.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 42,
        title: "Signs A-Boards",
        slug: "signs-a-boards",
        description:
          "Cupiditate consequatur corrupti necessitatibus itaque sed alias ut. Dolore voluptatibus vel quae repudiandae neque. A id nam rerum impedit saepe porro rerum. Non impedit sit architecto nihil.",
        meta_title: "Signs A-Boards",
        meta_description:
          "Est quisquam odit cupiditate recusandae velit reiciendis. Sit provident optio ea cumque quisquam libero. Dolorem animi voluptatem et harum alias. Id eius qui voluptas totam.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 43,
        title: "Vinyl Signage",
        slug: "vinyl-signage",
        description:
          "Qui distinctio dolor molestiae quo rem debitis. Similique repellat sint adipisci autem saepe.",
        meta_title: "Vinyl Signage",
        meta_description:
          "Nulla et totam amet rem quaerat numquam dolores. Accusantium doloribus tenetur doloribus dolorum omnis doloremque sunt dolores. Ullam dolores ex sed. Laudantium voluptatem aut sint doloremque ea id.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 44,
        title: "Banners",
        slug: "signage-banners",
        description:
          "Provident veritatis debitis quo voluptatem nihil ullam atque. Qui deleniti vitae nihil ut.",
        meta_title: "Signage Banners",
        meta_description:
          "Id rerum occaecati repudiandae molestiae autem. Necessitatibus totam culpa explicabo sed vel nesciunt. Consectetur nihil alias velit quod quo. Voluptatem sapiente velit vel debitis tempora.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 45,
        title: "Poster Printing",
        slug: "poster-printing",
        description:
          "Deleniti reiciendis quia sed a quidem. Saepe sapiente non eos similique beatae occaecati. Eos sapiente in autem ratione. Reiciendis quis enim laudantium veritatis veritatis. Odio iste perferendis tempora quibusdam aliquam cupiditate.",
        meta_title: "Poster Printing",
        meta_description:
          "Autem voluptatem labore maxime aut. Repellendus velit magni doloribus exercitationem soluta eum. Consequatur ea reiciendis cupiditate et.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 46,
        title: "Sign Printing",
        slug: "sign-printing",
        description:
          "Commodi sapiente animi facere incidunt tenetur optio qui nihil. Cum dicta vel nihil itaque id quo. Ullam enim repudiandae totam omnis distinctio officia sunt.",
        meta_title: "Sign Printing",
        meta_description:
          "Occaecati velit unde amet. Placeat expedita minima deleniti quam exercitationem quia quidem. Eos aut autem quia sed repellendus quaerat aut. Eligendi qui eveniet in quasi et quos.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 47,
        title: "Table Top Signage",
        slug: "table-top-signage",
        description:
          "Necessitatibus itaque dolor placeat iure enim aliquid accusantium. Nesciunt cum consectetur dolorem dignissimos unde.",
        meta_title: "Table Top Signage",
        meta_description:
          "Magni sed et iste omnis doloribus rerum. Totam fugit sequi facere velit velit sit adipisci provident. Aut placeat temporibus perspiciatis nostrum aut voluptatem necessitatibus.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 48,
        title: "Safety Signage",
        slug: "safety-signage",
        description:
          "Fuga soluta quibusdam molestias recusandae voluptas quod est et. Natus ut voluptatibus velit quo. Reiciendis dolore aspernatur eum dicta velit ex. Repudiandae tenetur consequatur et recusandae.",
        meta_title: "Safety Signage",
        meta_description:
          "Aut iusto aliquid excepturi quibusdam provident aperiam magni. Et voluptatem commodi quo odit consequuntur.",
        status: "Active",
        category_id: 41,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 49,
    title: "Stickers, Labels, Tags & Packaging",
    slug: "stickers-labels-tags-packaging",
    description:
      "Rem sunt natus vel corporis et nam quidem eligendi. Vero atque unde maxime totam aperiam impedit eos. Maxime nesciunt maiores esse. Voluptatum modi dolor voluptas dolores omnis et voluptate rerum.",
    meta_title: "Stickers, Labels, Tags & Packaging",
    meta_description:
      "Ea nihil voluptatem blanditiis. Vel iste a non ut esse animi est. Occaecati et non enim corrupti eum aperiam.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: null,
    offer_id: 1,
    children: [
      {
        id: 50,
        title: "Stickers By Shape",
        slug: "stickers-by-shape",
        description:
          "Omnis voluptatem animi quis fuga ipsam molestiae. Dolorum laboriosam id voluptas magni sit. Aut incidunt dolorem repellat nostrum corrupti. Et quisquam non cupiditate.",
        meta_title: "Stickers By Shape",
        meta_description:
          "Aut rerum commodi voluptatem quia. Error consequuntur cupiditate laudantium eum ea quia.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 51,
        title: "Stickers By Use",
        slug: "stickers-by-use",
        description:
          "Nostrum accusamus vel voluptatem consectetur recusandae doloremque debitis. Qui dolorem explicabo fuga. Sint impedit nihil enim quisquam ut non. Totam laborum nisi cupiditate unde.",
        meta_title: "Stickers By Use",
        meta_description:
          "Rerum non necessitatibus molestiae occaecati facilis ducimus laudantium. Et quia aliquam omnis ratione assumenda adipisci facilis. Consequatur suscipit voluptatibus doloribus omnis.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 52,
        title: "Stickers By Type",
        slug: "stickers-by-type",
        description:
          "Assumenda quam id eligendi reiciendis hic ipsam praesentium. Sequi unde tenetur pariatur temporibus quasi ipsa dolorem. Vitae tempora corporis occaecati. Ea ipsa rem debitis cum.",
        meta_title: "Stickers By Type",
        meta_description:
          "Voluptates est quis reprehenderit qui. Ad voluptatum similique ut sequi perferendis sit ad. Ad ut nihil praesentium. Qui consequatur adipisci quae dolore cupiditate enim. Animi ut ducimus eos aut.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 53,
        title: "Label By Use",
        slug: "label-by-use",
        description:
          "Alias aut incidunt velit alias autem iste natus. Autem hic in alias. Eos mollitia eos consequuntur est optio vel sunt. Odit quis est alias eveniet ut minima quibusdam.",
        meta_title: "Label By Use",
        meta_description:
          "Illo suscipit nesciunt minus quisquam itaque mollitia. Maiores sit iusto doloribus necessitatibus quos odit. Fuga velit sint eius officiis at. Consectetur voluptatibus et error non sint ducimus quod veniam. Voluptas voluptate excepturi neque laborum.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 54,
        title: "Label By Type",
        slug: "label-by-type",
        description:
          "Occaecati et enim aliquid ratione aut quos. Reiciendis debitis quasi qui amet natus aut fugit. Est sint aperiam reiciendis.",
        meta_title: "Label By Type",
        meta_description:
          "Illum corporis reprehenderit voluptate maxime incidunt cum voluptas. Accusantium dolor dolore et est quod. Expedita esse placeat expedita id accusamus enim. Qui quia tempore odit sunt qui. Ducimus odit dolores possimus repellat perferendis itaque dolorem.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 55,
        title: "Product Packaging",
        slug: "product-packaging",
        description:
          "Quidem dolorum id iusto ea totam. Expedita dolore sint temporibus repudiandae voluptate. Quis quam voluptatem perspiciatis exercitationem. Quibusdam suscipit voluptas corrupti aperiam numquam.",
        meta_title: "Product Packaging",
        meta_description:
          "Nemo eos aspernatur quod id consequatur. Est dolores vel nam et occaecati eum fugiat. Non expedita aut rerum aperiam voluptatem.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 56,
        title: "Shipping Packaging",
        slug: "shipping-packaging",
        description:
          "Possimus nostrum minima dolore ipsum quis unde qui. Qui atque voluptatum voluptates. Ut quidem ut cupiditate in facilis et. Distinctio eum ipsum beatae perspiciatis iure.",
        meta_title: "Shipping Packaging",
        meta_description:
          "Qui animi sunt eligendi ex ipsum et quis. Molestiae pariatur impedit ex accusantium doloribus. Dolores dolor vitae dolorum ut. Et quod ipsa voluptate et delectus dolor aut perspiciatis.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
      {
        id: 57,
        title: "Food Safe Packaging",
        slug: "food-safe-packaging",
        description:
          "Qui aut perspiciatis sit. Vero rem ut dolor ex consequatur itaque. Et nobis velit facere amet delectus iure expedita. Dicta eius voluptatem ut aspernatur et unde id.",
        meta_title: "Food Safe Packaging",
        meta_description:
          "Ut non consequatur quia explicabo enim et et. Accusamus similique aspernatur sequi est qui laudantium omnis. Facere voluptatem nihil rem laborum aperiam ut.",
        status: "Active",
        category_id: 49,
        created_at: null,
        updated_at: null,
        offer_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 58,
    title: "Merchandise & Clothing",
    slug: "merchandise-clothing",
    description:
      "Dolore sed minima aspernatur ut dolor quis. Porro quia inventore dolor neque ab minima accusantium saepe. Est delectus nesciunt quibusdam sit reiciendis et nesciunt.",
    meta_title: "Merchandise & Clothing",
    meta_description:
      "Adipisci aut aut quam praesentium tempore ducimus. Assumenda aliquam sunt perspiciatis ea. Vel ut velit porro qui distinctio. Eius accusamus voluptate ea qui modi.",
    status: "Active",
    category_id: null,
    created_at: null,
    updated_at: "2024-04-06T11:01:09.000000Z",
    offer_id: 1,
    children: [],
  },
];
