import Loader from "@/components/Loader/Loader";
import { useAuth } from "@/hooks/useAuth";
import useDebounce from "@/hooks/useDebounce";
import useToastMessage from "@/hooks/useToastMessage";
import { address_schema } from "@/lib/schema";
import { createAddressMutation } from "@/resolvers/mutation";
import { yupResolver } from "@hookform/resolvers/yup";
import { useMutation } from "@tanstack/react-query";
import axios from "axios";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";

/* const results = [
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "2",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951656,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1G",
    line_1: "2 Strone Road",
    line_2: "",
    line_3: "",
    premise: "2",
    longitude: 0.0331391,
    latitude: 51.5424006,
    eastings: 541087,
    northings: 184570,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071699",
    id: "paf_7951656",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "4",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951667,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1W",
    line_1: "4 Strone Road",
    line_2: "",
    line_3: "",
    premise: "4",
    longitude: 0.0331715,
    latitude: 51.542481,
    eastings: 541089,
    northings: 184579,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071701",
    id: "paf_7951667",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "6",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951678,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2J",
    line_1: "6 Strone Road",
    line_2: "",
    line_3: "",
    premise: "6",
    longitude: 0.0332439,
    latitude: 51.5424887,
    eastings: 541094,
    northings: 184580,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071703",
    id: "paf_7951678",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "8",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951689,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2Y",
    line_1: "8 Strone Road",
    line_2: "",
    line_3: "",
    premise: "8",
    longitude: 0.0333168,
    latitude: 51.5425055,
    eastings: 541099,
    northings: 184582,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071705",
    id: "paf_7951689",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "10",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951651,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1A",
    line_1: "10 Strone Road",
    line_2: "",
    line_3: "",
    premise: "10",
    longitude: 0.0333752,
    latitude: 51.5425224,
    eastings: 541103,
    northings: 184584,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071707",
    id: "paf_7951651",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "12",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951652,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1B",
    line_1: "12 Strone Road",
    line_2: "",
    line_3: "",
    premise: "12",
    longitude: 0.0334477,
    latitude: 51.5425302,
    eastings: 541108,
    northings: 184585,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071709",
    id: "paf_7951652",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "14",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951653,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1D",
    line_1: "14 Strone Road",
    line_2: "",
    line_3: "",
    premise: "14",
    longitude: 0.0335061,
    latitude: 51.5425471,
    eastings: 541112,
    northings: 184587,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071711",
    id: "paf_7951653",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "16",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951654,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1E",
    line_1: "16 Strone Road",
    line_2: "",
    line_3: "",
    premise: "16",
    longitude: 0.0335786,
    latitude: 51.5425549,
    eastings: 541117,
    northings: 184588,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071713",
    id: "paf_7951654",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "18",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951655,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1F",
    line_1: "18 Strone Road",
    line_2: "",
    line_3: "",
    premise: "18",
    longitude: 0.0336366,
    latitude: 51.5425629,
    eastings: 541121,
    northings: 184589,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071715",
    id: "paf_7951655",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "20",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951657,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1H",
    line_1: "20 Strone Road",
    line_2: "",
    line_3: "",
    premise: "20",
    longitude: 0.0337243,
    latitude: 51.5425883,
    eastings: 541127,
    northings: 184592,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071717",
    id: "paf_7951657",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "22",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951658,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1J",
    line_1: "22 Strone Road",
    line_2: "",
    line_3: "",
    premise: "22",
    longitude: 0.0337823,
    latitude: 51.5425963,
    eastings: 541131,
    northings: 184593,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071719",
    id: "paf_7951658",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "24",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951659,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1L",
    line_1: "24 Strone Road",
    line_2: "",
    line_3: "",
    premise: "24",
    longitude: 0.0338552,
    latitude: 51.542613,
    eastings: 541136,
    northings: 184595,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071721",
    id: "paf_7951659",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "26",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951660,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1N",
    line_1: "26 Strone Road",
    line_2: "",
    line_3: "",
    premise: "26",
    longitude: 0.0339132,
    latitude: 51.542621,
    eastings: 541140,
    northings: 184596,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071723",
    id: "paf_7951660",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "28",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951661,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1P",
    line_1: "28 Strone Road",
    line_2: "",
    line_3: "",
    premise: "28",
    longitude: 0.0339861,
    latitude: 51.5426377,
    eastings: 541145,
    northings: 184598,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "10014033663",
    id: "paf_7951661",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "30",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951662,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1Q",
    line_1: "30 Strone Road",
    line_2: "",
    line_3: "",
    premise: "30",
    longitude: 0.0340441,
    latitude: 51.5426457,
    eastings: 541149,
    northings: 184599,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071727",
    id: "paf_7951662",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "32",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951663,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1R",
    line_1: "32 Strone Road",
    line_2: "",
    line_3: "",
    premise: "32",
    longitude: 0.034642,
    latitude: 51.542751,
    eastings: 541192,
    northings: 184612,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "",
    id: "paf_7951663",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "34",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951664,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1S",
    line_1: "34 Strone Road",
    line_2: "",
    line_3: "",
    premise: "34",
    longitude: 0.0341898,
    latitude: 51.5426791,
    eastings: 541159,
    northings: 184603,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071731",
    id: "paf_7951664",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "36",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951665,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1T",
    line_1: "36 Strone Road",
    line_2: "",
    line_3: "",
    premise: "36",
    longitude: 0.0342619,
    latitude: 51.5426779,
    eastings: 541164,
    northings: 184603,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071733",
    id: "paf_7951665",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "38",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951666,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1U",
    line_1: "38 Strone Road",
    line_2: "",
    line_3: "",
    premise: "38",
    longitude: 0.0343199,
    latitude: 51.5426859,
    eastings: 541168,
    northings: 184604,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071735",
    id: "paf_7951666",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "40",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951668,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1X",
    line_1: "40 Strone Road",
    line_2: "",
    line_3: "",
    premise: "40",
    longitude: 0.0343928,
    latitude: 51.5427026,
    eastings: 541173,
    northings: 184606,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071737",
    id: "paf_7951668",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "42",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951669,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1Y",
    line_1: "42 Strone Road",
    line_2: "",
    line_3: "",
    premise: "42",
    longitude: 0.0344512,
    latitude: 51.5427196,
    eastings: 541177,
    northings: 184608,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071739",
    id: "paf_7951669",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "44",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951670,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "1Z",
    line_1: "44 Strone Road",
    line_2: "",
    line_3: "",
    premise: "44",
    longitude: 0.0345237,
    latitude: 51.5427273,
    eastings: 541182,
    northings: 184609,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071741",
    id: "paf_7951670",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "46",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951671,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2A",
    line_1: "46 Strone Road",
    line_2: "",
    line_3: "",
    premise: "46",
    longitude: 0.0345965,
    latitude: 51.542744,
    eastings: 541187,
    northings: 184611,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071743",
    id: "paf_7951671",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "48",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951672,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2B",
    line_1: "48 Strone Road",
    line_2: "",
    line_3: "",
    premise: "48",
    longitude: 0.034669,
    latitude: 51.5427518,
    eastings: 541192,
    northings: 184612,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071745",
    id: "paf_7951672",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "50",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951673,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2D",
    line_1: "50 Strone Road",
    line_2: "",
    line_3: "",
    premise: "50",
    longitude: 0.0347274,
    latitude: 51.5427687,
    eastings: 541196,
    northings: 184614,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071747",
    id: "paf_7951673",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "52",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951674,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2E",
    line_1: "52 Strone Road",
    line_2: "",
    line_3: "",
    premise: "52",
    longitude: 0.0347999,
    latitude: 51.5427765,
    eastings: 541201,
    northings: 184615,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071749",
    id: "paf_7951674",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "54",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951675,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2F",
    line_1: "54 Strone Road",
    line_2: "",
    line_3: "",
    premise: "54",
    longitude: 0.0348587,
    latitude: 51.5428024,
    eastings: 541205,
    northings: 184618,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071751",
    id: "paf_7951675",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "56",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951676,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2G",
    line_1: "56 Strone Road",
    line_2: "",
    line_3: "",
    premise: "56",
    longitude: 0.0349316,
    latitude: 51.5428191,
    eastings: 541210,
    northings: 184620,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071753",
    id: "paf_7951676",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "58",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951677,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2H",
    line_1: "58 Strone Road",
    line_2: "",
    line_3: "",
    premise: "58",
    longitude: 0.0349896,
    latitude: 51.5428271,
    eastings: 541214,
    northings: 184621,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071755",
    id: "paf_7951677",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "60",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951679,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2L",
    line_1: "60 Strone Road",
    line_2: "",
    line_3: "",
    premise: "60",
    longitude: 0.0350773,
    latitude: 51.5428526,
    eastings: 541220,
    northings: 184624,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071757",
    id: "paf_7951679",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "62",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951680,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2N",
    line_1: "62 Strone Road",
    line_2: "",
    line_3: "",
    premise: "62",
    longitude: 0.0351213,
    latitude: 51.5428698,
    eastings: 541223,
    northings: 184626,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071759",
    id: "paf_7951680",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "64",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951681,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2P",
    line_1: "64 Strone Road",
    line_2: "",
    line_3: "",
    premise: "64",
    longitude: 0.0351938,
    latitude: 51.5428775,
    eastings: 541228,
    northings: 184627,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071761",
    id: "paf_7951681",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "66",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951682,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2Q",
    line_1: "66 Strone Road",
    line_2: "",
    line_3: "",
    premise: "66",
    longitude: 0.0352522,
    latitude: 51.5428945,
    eastings: 541232,
    northings: 184629,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071763",
    id: "paf_7951682",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "68",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951683,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2R",
    line_1: "68 Strone Road",
    line_2: "",
    line_3: "",
    premise: "68",
    longitude: 0.0353247,
    latitude: 51.5429022,
    eastings: 541237,
    northings: 184630,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071765",
    id: "paf_7951683",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "70",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951684,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2S",
    line_1: "70 Strone Road",
    line_2: "",
    line_3: "",
    premise: "70",
    longitude: 0.0353975,
    latitude: 51.542919,
    eastings: 541242,
    northings: 184632,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071767",
    id: "paf_7951684",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "72",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951685,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2T",
    line_1: "72 Strone Road",
    line_2: "",
    line_3: "",
    premise: "72",
    longitude: 0.035456,
    latitude: 51.5429359,
    eastings: 541246,
    northings: 184634,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071769",
    id: "paf_7951685",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "74",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951686,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2U",
    line_1: "74 Strone Road",
    line_2: "",
    line_3: "",
    premise: "74",
    longitude: 0.0355428,
    latitude: 51.5429434,
    eastings: 541252,
    northings: 184635,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071771",
    id: "paf_7951686",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "76",
    building_name: "",
    sub_building_name: "First Floor Flat",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 57559878,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3N",
    line_1: "First Floor Flat",
    line_2: "76 Strone Road",
    line_3: "",
    premise: "First Floor Flat, 76",
    longitude: 0.0356149,
    latitude: 51.5429422,
    eastings: 541257,
    northings: 184635,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "10023997873",
    id: "paf_57559878",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "76",
    building_name: "",
    sub_building_name: "Ground Floor Flat",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951687,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2W",
    line_1: "Ground Floor Flat",
    line_2: "76 Strone Road",
    line_3: "",
    premise: "Ground Floor Flat, 76",
    longitude: 0.0356149,
    latitude: 51.5429422,
    eastings: 541257,
    northings: 184635,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071773",
    id: "paf_7951687",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "78",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951688,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2X",
    line_1: "78 Strone Road",
    line_2: "",
    line_3: "",
    premise: "78",
    longitude: 0.0356733,
    latitude: 51.5429591,
    eastings: 541261,
    northings: 184637,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071775",
    id: "paf_7951688",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "80",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951690,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "2Z",
    line_1: "80 Strone Road",
    line_2: "",
    line_3: "",
    premise: "80",
    longitude: 0.0357458,
    latitude: 51.5429669,
    eastings: 541266,
    northings: 184638,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071777",
    id: "paf_7951690",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "82",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951691,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3A",
    line_1: "82 Strone Road",
    line_2: "",
    line_3: "",
    premise: "82",
    longitude: 0.0358042,
    latitude: 51.5429838,
    eastings: 541270,
    northings: 184640,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071779",
    id: "paf_7951691",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "84",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951692,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3B",
    line_1: "84 Strone Road",
    line_2: "",
    line_3: "",
    premise: "84",
    longitude: 0.0358767,
    latitude: 51.5429916,
    eastings: 541275,
    northings: 184641,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071781",
    id: "paf_7951692",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "86",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951693,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3D",
    line_1: "86 Strone Road",
    line_2: "",
    line_3: "",
    premise: "86",
    longitude: 0.0359351,
    latitude: 51.5430085,
    eastings: 541279,
    northings: 184643,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071783",
    id: "paf_7951693",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "88",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951694,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3E",
    line_1: "88 Strone Road",
    line_2: "",
    line_3: "",
    premise: "88",
    longitude: 0.0360076,
    latitude: 51.5430163,
    eastings: 541284,
    northings: 184644,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071785",
    id: "paf_7951694",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "90",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951695,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3F",
    line_1: "90 Strone Road",
    line_2: "",
    line_3: "",
    premise: "90",
    longitude: 0.0360664,
    latitude: 51.5430422,
    eastings: 541288,
    northings: 184647,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071787",
    id: "paf_7951695",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "92",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951696,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3G",
    line_1: "92 Strone Road",
    line_2: "",
    line_3: "",
    premise: "92",
    longitude: 0.0361393,
    latitude: 51.543059,
    eastings: 541293,
    northings: 184649,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071789",
    id: "paf_7951696",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
  {
    postcode: "E7 8EU",
    postcode_inward: "8EU",
    postcode_outward: "E7",
    post_town: "London",
    dependant_locality: "",
    double_dependant_locality: "",
    thoroughfare: "Strone Road",
    dependant_thoroughfare: "",
    building_number: "94",
    building_name: "",
    sub_building_name: "",
    po_box: "",
    department_name: "",
    organisation_name: "",
    udprn: 7951697,
    postcode_type: "S",
    su_organisation_indicator: "",
    delivery_point_suffix: "3H",
    line_1: "94 Strone Road",
    line_2: "",
    line_3: "",
    premise: "94",
    longitude: 0.0361973,
    latitude: 51.5430669,
    eastings: 541297,
    northings: 184650,
    country: "England",
    traditional_county: "Essex",
    administrative_county: "",
    postal_county: "London",
    county: "London",
    district: "Newham",
    ward: "Green Street East",
    uprn: "46071791",
    id: "paf_7951697",
    country_iso: "GBR",
    country_iso_2: "GB",
    county_code: "",
    language: "en",
    umprn: "",
    dataset: "paf",
  },
];
 */
const NewAddressForm = () => {
  const showToastMessage = useToastMessage();
  const { isAuthenticated, user, session } = useAuth();
  const [results, set_results] = useState([]);
  const [post_code, set_post_code] = useState("");
  const [selectedAddress, set_selectedAddress] = useState(null);
  const [manually, set_manually] = useState(false);

  const { mutate, isPending } = useMutation({
    mutationKey: "addAddress",
    mutationFn: createAddressMutation,
  });

  const {
    register,
    setValue,
    reset,
    handleSubmit,
    getValues,
    watch,
    formState: { errors },
  } = useForm({
    defaultValues: {
      first_name: "",
      last_name: "",
      company_name: "",
      address: "",
      address_2: "",
      town: "",
      postcode: "",
      country: "",
      delivery_mobile_number: "",
      delivery_email: "",
      default: false,
    },
    resolver: yupResolver(address_schema),
  });

  const onSubmit = (data) => {
    const variables = {
      first_name: data.first_name,
      last_name: data.last_name,
      company_name: data.company_name,
      line_1: data.address,
      line_2: data.address_2 || "",
      country: data.country,
      town: data.town,
      post_code: post_code,
      address: data.address,
      email: data.delivery_email,
      phone: data.delivery_mobile_number,
      is_default: data.default ? 1 : 0,
      user_id: user?.id,
      type: "shipping",
    };

    mutate(
      {
        variables,
        token: session?.token,
      },
      {
        onSuccess: () => {
          toast.success("Address added successfully");
          reset();
          set_post_code("");
          set_results([]);
        },
        onError: (error) => {
          showToastMessage(error.response.data.message || "An error occurred");
        },
      }
    );
  };

  const search = async (searchQuery) => {
    try {
      /*  const response = await axios.get(
        `https://postcodes.io/postcodes/${searchQuery}`,
        {
          params: { q: searchQuery },
        }
        console.log("Search results", response.data);
      ); */
      const addresses = JSON.parse(localStorage.getItem("addresses")) || [];

      set_results(addresses);
    } catch (error) {
      console.error("Error fetching search results", error);
    }
  };

  const debouncedSearch = useDebounce(search, 2000);

  const handlePostCode = (e) => {
    set_post_code(e.target.value);
    debouncedSearch(e.target.value);
  };

  const onSelectAddress = (e) => {
    set_selectedAddress(e.target.value);
  };

  /*   useEffect(() => {
    window && window.localStorage.setItem("addresses", JSON.stringify(results));
  }, []); */

  useEffect(() => {
    if (selectedAddress && !manually && results.length > 0) {
      const address = results.find((address) => address.id === selectedAddress);

      setValue("address", address.line_1, { shouldValidate: true });
      setValue("town", address.post_town, { shouldValidate: true });
      setValue("postcode", address.postcode, { shouldValidate: true });
      setValue("country", address.country, { shouldValidate: true });
    }
  }, [selectedAddress, manually, results, setValue]);

  return (
    <div>
      <div className="px-3 py-2 md:py-3">
        <div className="flex items-center justify-between mb-2 md:mb-3 ">
          <h6 className="px-2 py-5 text-base font-semibold text-black ">
            Add new Delivery Addresses
          </h6>
          <div>
            <p className="text-[12px] md:text-base font-normal text-red-500">
              Required*
            </p>
            <Link href="/my-account/delivery-payment">
              {" "}
              <p className="text-sm font-normal underline md:text-base text-primary">
                Select existing address
              </p>
            </Link>
          </div>
        </div>

        {/* ---------- */}
        <div className="flex ">
          <p className="text-base  font-medium text-secondgraphy px-2 w-[65%]">
            PostCode*
          </p>
          <div className="w-full">
            <input
              type="text"
              placeholder="Enter Post code"
              className="block w-full px-2 py-2 mb-2 border rounded-md outline-none border-secondgraphy "
              value={post_code}
              onChange={handlePostCode}
            />
          </div>
        </div>
        {results.length > 0 && (
          <>
            <div className="flex mt-3">
              <p className="text-base  font-medium text-secondgraphy px-2 w-[65%]">
                Select Address
              </p>
              <div className="w-full">
                <select
                  name="address_select"
                  id="address_select"
                  className="block w-full px-2 py-2 mb-2 border rounded-md outline-none border-secondgraphy"
                  value={selectedAddress}
                  onChange={onSelectAddress}
                >
                  <option value="">Select Address</option>
                  {results.map((address) => (
                    <option
                      key={address.id}
                      value={address.id}
                      data-id={address.id}
                    >
                      {address.line_1}, {address.post_town}, {address.postcode}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div className="flex mt-3">
              <p className="text-base invisible  font-medium text-secondgraphy px-2 w-[65%]">
                Select Address
              </p>
              <div>
                <input
                  type="checkbox"
                  id="address"
                  name="address"
                  for="address"
                  onChange={(e) => set_manually(e.target.checked)}
                />
                <label
                  for="address"
                  className="ml-3 text-sm font-medium md:text-base text-secondgraphy "
                >
                  Enter Addresses Manualy
                </label>
              </div>
            </div>
          </>
        )}
      </div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="border"></div>
        <div className="px-2 mb-2 md:px-5 md:mb-5">
          <div className="flex mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Frist Name*
            </label>

            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                name="first_name"
                {...register("first_name")}
              />
              {errors.first_name && (
                <p className="text-red-500">{errors.first_name.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Last Name*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                name="last_name"
                {...register("last_name")}
              />
              {errors.last_name && (
                <p className="text-red-500">{errors.last_name.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Compony Name*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                name="company_name"
                {...register("company_name")}
              />
              {errors.company_name && (
                <p className="text-red-500">{errors.company_name.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Address line 1*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 border rounded-md shadow-md outline-none border-secondgraphy"
                name="address"
                {...register("address")}
              />
              {errors.address && (
                <p className="text-red-500">{errors.address.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Address line 2*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 border rounded-md shadow-md outline-none border-secondgraphy"
                name="address_2"
                {...register("address_2")}
              />
              {errors.address_2 && (
                <p className="text-red-500">{errors.address_2.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Town*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                name="town"
                {...register("town")}
              />
              {errors.town && (
                <p className="text-red-500">{errors.town.message}</p>
              )}
            </div>
          </div>
          <div className="flex mt-2 md:mt-5">
            <label className="w-[40%] font-medium text-typography text-base ">
              Country*
            </label>
            <div className="w-[60%]">
              <input
                type="text"
                className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                name="country"
                {...register("country")}
              />
              {errors.country && (
                <p className="text-red-500">{errors.country.message}</p>
              )}
            </div>
          </div>
        </div>
        <div className="bg-[#faefc9] p-2 md:p-5">
          <div>
            <h5 className="mb-2 text-base font-semibold text-typography ">
              How would like to be update on your Delivery
            </h5>
            <p className="mb-5 text-sm font-normal md:text-base text-typography">
              Create print-ready artwork swiftly with our Online Designer. This
              designer enables you to add your own images, text, or graphics and
              see your final printed designs come to life. We even provide
              interactive 3D models for certain products, allowing you to
              visualise and modify your final product.
            </p>

            <div className="flex ">
              <label className="w-[40%] text-secondgraphy font-semibold  text-sm md:text-base ">
                Delivery contact Mobile number
              </label>

              <div className="w-[60%]">
                <input
                  type="text"
                  className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                  name="delivery_mobile_number"
                  {...register("delivery_mobile_number")}
                />
                {errors.delivery_mobile_number && (
                  <p className="text-red-500">
                    {errors.delivery_mobile_number.message}
                  </p>
                )}
              </div>
            </div>
            <div className="flex mt-2 md:mt-4 ">
              <label className="w-[40%] text-secondgraphy font-semibold  text-sm md:text-base ">
                Delivery Enter Email
              </label>

              <div className="w-[60%]">
                <input
                  type="email"
                  className="block w-full px-2 py-2 mb-2 -mt-2 border rounded-md outline-none border-secondgraphy"
                  name="delivery_email"
                  {...register("delivery_email")}
                />
                {errors.delivery_email && (
                  <p className="text-red-500">
                    {errors.delivery_email.message}
                  </p>
                )}
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-center py-2 md:py-5">
          <div>
            {/* <div>
              <input
                type="checkbox"
                id="saveaddress"
                name="address"
                for="address"
              />
              <label
                for="saveaddress"
                className="ml-3 text-sm font-medium md:text-base text-secondgraphy "
              >
                Save as Address
              </label>
            </div> */}
            <div>
              <input
                type="checkbox"
                id="default"
                name="default"
                defaultChecked={getValues("default")}
                onChange={(e) => setValue("default", e.target.checked)}
              />
              <label
                for="default"
                className="ml-3 text-sm font-medium md:text-base text-secondgraphy "
              >
                Save as default Delivery Address
              </label>
            </div>
          </div>
        </div>
        <div className="px-2 mb-5 md:px-5 ">
          <button
            type="submit"
            className="w-full py-1 text-base font-bold border rounded-md md:py-2 bg-primary text-secondgraphy"
          >
            {isPending ? "Adding Address..." : "Add Address"}
          </button>
        </div>
      </form>
    </div>
  );
};

export default NewAddressForm;
