import React from "react";

const menuCategories = [
  {
    id: 1,
    name: "Large format Printing",
    slug: "Large-format-Printing",
    description: "lorem",
    meta_title: "lorem",
    meta_description: "lorem",
    meta_keywords: "lorem",
    status: "1",
    offer_id: null,
    category_id: null,
    created_by: 0,
    modified_by: 0,
    created_at: null,
    updated_at: null,
    deleted_at: null,
    children: [
      {
        id: 2,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
      {
        id: 5,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    name: "Large format Printing",
    slug: "Large-format-Printing",
    description: "lorem",
    meta_title: "lorem",
    meta_description: "lorem",
    meta_keywords: "lorem",
    status: "1",
    offer_id: null,
    category_id: null,
    created_by: 0,
    modified_by: 0,
    created_at: null,
    updated_at: null,
    deleted_at: null,
    children: [
      {
        id: 2,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
      {
        id: 5,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    name: "Large format Printing",
    slug: "Large-format-Printing",
    description: "lorem",
    meta_title: "lorem",
    meta_description: "lorem",
    meta_keywords: "lorem",
    status: "1",
    offer_id: null,
    category_id: null,
    created_by: 0,
    modified_by: 0,
    created_at: null,
    updated_at: null,
    deleted_at: null,
    children: [
      {
        id: 2,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
      {
        id: 5,
        name: "a-board",
        slug: "a-board",
        description: "lorem Lorem Lorem ",
        meta_title: "a-board",
        meta_description: "lorem Lorem Lorem ",
        meta_keywords: "lorem Lorem Lorem ",
        status: "1",
        offer_id: null,
        category_id: 1,
        created_by: 0,
        modified_by: 0,
        created_at: null,
        updated_at: null,
        deleted_at: null,
        children: [
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
          {
            id: 3,
            name: "A-frames",
            slug: "a-frames",
            description: "lorem",
            meta_title: "lorem",
            meta_description: "lorem",
            meta_keywords: "lorem",
            status: "1",
            offer_id: null,
            category_id: 2,
            created_by: 0,
            modified_by: 0,
            created_at: null,
            updated_at: null,
            deleted_at: null,
            children: [],
          },
        ],
      },
    ],
  },
];

const Nav = () => {
  return (
    <nav>
      <ul className="flex items-center justify-center gap-4 main-menu group">
        {menuCategories.map((menu) => {
          return (
            <li key={menu.id} className=" category_item max-w-36 group">
              <a href={menu.slug}>{menu.name}</a>
              <div className=" group-hover:block hover:block">
                {menu.children.length > 0 && (
                  <ul>
                    {menu.children.map((child) => {
                      return (
                        <li key={child.id}>
                          <a href={child.slug}>{child.name}</a>
                          {child.children.length > 0 && (
                            <ul>
                              {child.children.map((grandChild) => {
                                return (
                                  <li key={grandChild.id}>
                                    <a href={grandChild.slug}>
                                      {grandChild.name}
                                    </a>
                                  </li>
                                );
                              })}
                            </ul>
                          )}
                        </li>
                      );
                    })}
                  </ul>
                )}
              </div>
            </li>
          );
        })}
      </ul>
    </nav>
  );
};

export default Nav;
